# Generated by Django 5.2.1 on 2025-05-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='adress',
            new_name='address',
        ),
    ]
